// Copyright (c) 2026 Juancarlo Añez (apalala@gmail.com)
// SPDX-License-Identifier: Apache-2.0

package peg

import (
	"fmt"
	"strings"
	"unicode"
	"unicode/utf8"
)

// ModelRepr generates Go source code for model types and conversion functions
// from a compiled Grammar. The output is a Go package with struct types for each
// rule that has a type annotation (::TypeName), and FromTree functions that
// convert folded parse trees into model instances.
func ModelRepr(g Grammar, pkg string) string {
	var buf strings.Builder

	buf.WriteString("// Code generated by ogo -g. DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg))
	buf.WriteString("import (\n")
	buf.WriteString("\t\"fmt\"\n\n")
	buf.WriteString("\t\"github.com/neogeny/ogopego/pkg/trees\"\n")
	buf.WriteString(")\n\n")

	type ruleInfo struct {
		rule     *Rule
		typeName string
		named    []namedField
		hasNames bool
	}

	var infos []ruleInfo
	for _, r := range g.Rules {
		if len(r.Params) == 0 {
			continue
		}
		tn := r.Params[0]
		var fields []namedField
		collectNamed(&fields, r.Exp)
		infos = append(infos, ruleInfo{
			rule:     r,
			typeName: tn,
			named:    fields,
			hasNames: len(fields) > 0,
		})
	}

	if len(infos) == 0 {
		buf.WriteString("// No rules with type annotations found.\n")
		return buf.String()
	}

	for _, ri := range infos {
		if ri.hasNames {
			buf.WriteString(fmt.Sprintf("type %s struct {\n", ri.typeName))
			for _, f := range ri.named {
				buf.WriteString(fmt.Sprintf("\t%s %s\n", f.goName, f.goType))
			}
			buf.WriteString("}\n\n")
		} else {
			buf.WriteString(fmt.Sprintf("// %s is generated from rule %s (no named elements).\n", ri.typeName, ri.rule.Name))
			buf.WriteString(fmt.Sprintf("type %s struct {\n", ri.typeName))
			buf.WriteString("\tValue string\n")
			buf.WriteString("}\n\n")
		}
	}

	for _, ri := range infos {
		buf.WriteString(fmt.Sprintf("func %sFromTree(tree trees.Tree) (*%s, error) {\n", ri.typeName, ri.typeName))

		if ri.hasNames {
			buf.WriteString("\tm, ok := tree.(*trees.MapNode)\n")
			buf.WriteString("\tif !ok {\n")
			buf.WriteString("\t\tn, ok := tree.(*trees.Node)\n")
			buf.WriteString("\t\tif !ok {\n")
			buf.WriteString(fmt.Sprintf("\t\t\treturn nil, fmt.Errorf(\"%sFromTree: expected Node or MapNode, got %%T\", tree)\n", ri.typeName))
			buf.WriteString("\t\t}\n")
			buf.WriteString(fmt.Sprintf("\t\treturn %sFromTree(n.Tree)\n", ri.typeName))
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\treturn &%s{\n", ri.typeName))
			for _, f := range ri.named {
				buf.WriteString(fmt.Sprintf("\t\t%s: m.Entries[\"%s\"].(*trees.Text).Value,\n", f.goName, f.name))
			}
			buf.WriteString("\t}, nil\n")
		} else {
			buf.WriteString("\tn, ok := tree.(*trees.Node)\n")
			buf.WriteString("\tif !ok {\n")
			buf.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"%sFromTree: expected *trees.Node, got %%T\", tree)\n", ri.typeName))
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\treturn &%s{Value: n.Tree.(*trees.Text).Value}, nil\n", ri.typeName))
		}

		buf.WriteString("}\n\n")
	}

	return buf.String()
}

type namedField struct {
	name   string
	goName string
	goType string
}

func collectNamed(fields *[]namedField, exp Model) {
	switch e := exp.(type) {
	case *Named:
		gt := "string"
		findTypeFromExp(e.Exp, func(tn string) {
			gt = "*" + tn
		})
		*fields = append(*fields, namedField{
			name:   e.Name,
			goName: capitalise(e.Name),
			goType: gt,
		})
	case *NamedList:
		gt := "[]string"
		findTypeFromExp(e.Exp, func(tn string) {
			gt = "[]*" + tn
		})
		*fields = append(*fields, namedField{
			name:   e.Name,
			goName: capitalise(e.Name),
			goType: gt,
		})
	case *Sequence:
		for _, item := range e.Sequence {
			collectNamed(fields, item)
		}
	case *Choice:
		for _, opt := range e.Options {
			collectNamed(fields, opt.Exp)
		}
	case *Option:
		collectNamed(fields, e.Exp)
	case *Group:
		collectNamed(fields, e.Exp)
	case *Closure:
		collectNamed(fields, e.Exp)
	case *PositiveClosure:
		collectNamed(fields, e.Exp)
	case *Gather:
		collectNamed(fields, e.Exp)
	case *PositiveGather:
		collectNamed(fields, e.Exp)
	case *Join:
		collectNamed(fields, e.Exp)
	case *PositiveJoin:
		collectNamed(fields, e.Exp)
	case *Optional:
		collectNamed(fields, e.Exp)
	case *Override:
		collectNamed(fields, e.Exp)
	case *OverrideList:
		collectNamed(fields, e.Exp)
	case *Synth:
		collectNamed(fields, e.Exp)
	case *SkipGroup:
		collectNamed(fields, e.Exp)
	}
}

func findTypeFromExp(exp Model, use func(string)) {
	switch e := exp.(type) {
	case *Call:
		if len(e.rule.Params) > 0 {
			use(e.rule.Params[0])
		}
	case *Group:
		findTypeFromExp(e.Exp, use)
	case *Sequence:
		for _, item := range e.Sequence {
			findTypeFromExp(item, use)
		}
	}
}

func capitalise(s string) string {
	if s == "" {
		return s
	}
	firstRune, size := utf8.DecodeRuneInString(s)
	return string(unicode.ToUpper(firstRune)) + s[size:]
}
