// Copyright (c) 2026 Juancarlo Añez (apalala@gmail.com)
// SPDX-License-Identifier: Apache-2.0

package tool

import (
	"fmt"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/neogeny/ogopego/pkg/peg"
)

// ModelRepr generates Go source code for model types and conversion functions
// from a compiled Grammar. The output is a Go package with struct types for each
// rule that has a type annotation (::TypeName), and FromTree functions that
// convert folded parse trees into model instances.
func ModelRepr(g peg.Grammar, pkg string) string {
	rules := g.RuleMap()

	type ruleInfo struct {
		rule     *peg.Rule
		typeName string
		fields   []fieldDef
	}

	var infos []ruleInfo
	for _, r := range g.Rules {
		if len(r.Params) == 0 {
			continue
		}
		tn := r.Params[0]
		var fields []fieldDef
		collectFields(&fields, r.Exp, rules)
		infos = append(infos, ruleInfo{
			rule:     r,
			typeName: tn,
			fields:   fields,
		})
	}

	var buf strings.Builder
	buf.WriteString("// Code generated by ogo -g. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	buf.WriteString("import (\n")
	buf.WriteString("\t\"fmt\"\n\n")
	buf.WriteString("\t\"github.com/neogeny/ogopego/pkg/trees\"\n")
	buf.WriteString(")\n\n")

	if len(infos) == 0 {
		buf.WriteString("// No rules with type annotations found.\n")
		return buf.String()
	}

	for _, ri := range infos {
		if len(ri.fields) > 0 {
			fmt.Fprintf(&buf, "type %s struct {\n", ri.typeName)
			for _, f := range ri.fields {
				fmt.Fprintf(&buf, "\t%s %s\n", f.goName, f.goType)
			}
			buf.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&buf, "type %s struct {\n", ri.typeName)
			buf.WriteString("\tValue any\n")
			buf.WriteString("}\n\n")
		}
	}

	for _, ri := range infos {
		fmt.Fprintf(&buf, "func %sFromTree(tree any) (*%s, error) {\n", ri.typeName, ri.typeName)
		buf.WriteString("\tn, ok := tree.(*trees.Node)\n")
		buf.WriteString("\tif !ok {\n")
		fmt.Fprintf(&buf, "\t\treturn nil, fmt.Errorf(\"%sFromTree: expected *trees.Node, got %%T\", tree)\n", ri.typeName)
		buf.WriteString("\t}\n")

		if len(ri.fields) > 0 {
			buf.WriteString("\tm, ok := n.Tree.(map[string]any)\n")
			buf.WriteString("\tif !ok {\n")
			fmt.Fprintf(&buf, "\t\treturn nil, fmt.Errorf(\"%sFromTree: expected map, got %%T\", n.Tree)\n", ri.typeName)
			buf.WriteString("\t}\n")
			buf.WriteString(fmt.Sprintf("\tvar result %s\n", ri.typeName))

			needsErr := false
			for _, f := range ri.fields {
				switch {
				case f.fromNamedList && strings.HasPrefix(f.goType, "[]*"):
					needsErr = true
				case !f.fromNamedList && strings.HasPrefix(f.goType, "[]*"):
					needsErr = true
				case strings.HasPrefix(f.goType, "*"):
					needsErr = true
				}
			}
			if needsErr {
				buf.WriteString("\tvar err error\n")
			}
			buf.WriteString("\n")

			for _, f := range ri.fields {
				innerType := strings.TrimPrefix(f.goType, "[]")
				switch {
				case f.fromNamedList && strings.HasPrefix(f.goType, "[]*"):
					// NamedList with typed refs — entry is *trees.TreeSeq
					fmt.Fprintf(&buf, "\tif v, ok := m[\"%s\"]; ok {\n", f.name)
					buf.WriteString("\t\tseq, ok := v.(*trees.TreeSeq)\n")
					buf.WriteString("\t\tif !ok {\n")
					fmt.Fprintf(&buf, "\t\t\treturn nil, fmt.Errorf(\"%s.%s: expected TreeSeq, got %%T\", v)\n", ri.typeName, f.goName)
					buf.WriteString("\t\t}\n")
					fmt.Fprintf(&buf, "\t\tresult.%s = make(%s, len(seq.Items))\n", f.goName, f.goType)
					buf.WriteString("\t\tfor i, item := range seq.Items {\n")
					fmt.Fprintf(&buf, "\t\t\tresult.%s[i], err = %sFromTree(item)\n", f.goName, innerType)
					buf.WriteString("\t\t\tif err != nil {\n")
					fmt.Fprintf(&buf, "\t\t\t\treturn nil, fmt.Errorf(\"%s.%s[%%d]: %%w\", i, err)\n", ri.typeName, f.goName)
					buf.WriteString("\t\t\t}\n")
					buf.WriteString("\t\t}\n")
					buf.WriteString("\t}\n\n")

				case f.fromNamedList && strings.HasPrefix(f.goType, "[]"):
					// NamedList of string — entry is *trees.TreeSeq
					fmt.Fprintf(&buf, "\tif v, ok := m[\"%s\"]; ok {\n", f.name)
					buf.WriteString("\t\tseq, ok := v.(*trees.TreeSeq)\n")
					buf.WriteString("\t\tif !ok {\n")
					fmt.Fprintf(&buf, "\t\t\treturn nil, fmt.Errorf(\"%s.%s: expected TreeSeq, got %%T\", v)\n", ri.typeName, f.goName)
					buf.WriteString("\t\t}\n")
					fmt.Fprintf(&buf, "\t\tresult.%s = make(%s, len(seq.Items))\n", f.goName, f.goType)
					buf.WriteString("\t\tfor i, item := range seq.Items {\n")
					fmt.Fprintf(&buf, "\t\t\tresult.%s[i] = item.(string)\n", f.goName)
					buf.WriteString("\t\t}\n")
					buf.WriteString("\t}\n\n")
				case !f.fromNamedList && strings.HasPrefix(f.goType, "[]*"):
					// Named with list-wrapped typed ref — entry is *trees.List
					fmt.Fprintf(&buf, "\tif v, ok := m[\"%s\"]; ok {\n", f.name)
					buf.WriteString("\t\tlist, ok := v.(*trees.List)\n")
					buf.WriteString("\t\tif !ok {\n")
					fmt.Fprintf(&buf, "\t\t\treturn nil, fmt.Errorf(\"%s.%s: expected List, got %%T\", v)\n", ri.typeName, f.goName)
					buf.WriteString("\t\t}\n")
					fmt.Fprintf(&buf, "\t\tresult.%s = make(%s, len(list.Items))\n", f.goName, f.goType)
					buf.WriteString("\t\tfor i, item := range list.Items {\n")
					fmt.Fprintf(&buf, "\t\t\tresult.%s[i], err = %sFromTree(item)\n", f.goName, innerType)
					buf.WriteString("\t\t\tif err != nil {\n")
					fmt.Fprintf(&buf, "\t\t\t\treturn nil, fmt.Errorf(\"%s.%s[%%d]: %%w\", i, err)\n", ri.typeName, f.goName)
					buf.WriteString("\t\t\t}\n")
					buf.WriteString("\t\t}\n")
					buf.WriteString("\t}\n\n")

				case strings.HasPrefix(f.goType, "*"):
					// Named with typed call — extract from *trees.Node (nil-safe for Optional)
					fmt.Fprintf(&buf, "\tif v, ok := m[\"%s\"]; ok {\n", f.name)
					buf.WriteString("\t\tif n, ok := v.(*trees.Node); ok {\n")
					fmt.Fprintf(&buf, "\t\t\tresult.%s, err = %sFromTree(n)\n", f.goName, f.goType[1:])
					buf.WriteString("\t\t\tif err != nil {\n")
					fmt.Fprintf(&buf, "\t\t\t\treturn nil, fmt.Errorf(\"%s.%s: %%w\", err)\n", ri.typeName, f.goName)
					buf.WriteString("\t\t\t}\n")
					buf.WriteString("\t\t}\n")
					buf.WriteString("\t}\n\n")

			case f.goType == "string":
				// Named with pattern/token — entry is string
				fmt.Fprintf(&buf, "\tif v, ok := m[\"%s\"]; ok {\n", f.name)
				fmt.Fprintf(&buf, "\t\tresult.%s = v.(string)\n", f.goName)
					buf.WriteString("\t}\n\n")

				default:
					// Named with untyped/unknown inner — assign as any
					fmt.Fprintf(&buf, "\tif v, ok := m[\"%s\"]; ok {\n", f.name)
					fmt.Fprintf(&buf, "\t\tresult.%s = v\n", f.goName)
					buf.WriteString("\t}\n\n")
				}
			}

			buf.WriteString("\treturn &result, nil\n")
		} else {
			buf.WriteString(fmt.Sprintf("\treturn &%s{Value: n.Tree}, nil\n", ri.typeName))
		}

		buf.WriteString("}\n\n")
	}

	return buf.String()
}

type fieldDef struct {
	name          string
	goName        string
	goType        string
	fromNamedList bool
}

// collectFields walks a peg.Model expression tree and collects named fields.
// It discovers *peg.Named and *peg.NamedList nodes at compile time so the
// generated FromTree can extract them from the folded map at runtime.
func collectFields(fields *[]fieldDef, exp peg.Model, rules map[string]*peg.Rule) {
	switch e := exp.(type) {
	case *peg.Named:
		tname := resolvedTypeName(e.Exp, rules)
		var gt string
		switch {
		case tname != "" && isListExpr(e.Exp):
			gt = "[]*" + tname
		case tname != "":
			gt = "*" + tname
		case isConstantText(e.Exp, rules):
			gt = "string"
		default:
			gt = "any"
		}
		*fields = append(*fields, fieldDef{
			name:          e.Name,
			goName:        capitalise(e.Name),
			goType:        gt,
			fromNamedList: false,
		})
	case *peg.NamedList:
		tname := resolvedTypeName(e.Exp, rules)
		var gt string
		switch {
		case tname != "":
			gt = "[]*" + tname
		case isConstantText(e.Exp, rules):
			gt = "[]string"
		default:
			gt = "[]any"
		}
		*fields = append(*fields, fieldDef{
			name:          e.Name,
			goName:        capitalise(e.Name),
			goType:        gt,
			fromNamedList: true,
		})
	case *peg.Sequence:
		for _, item := range e.Sequence {
			collectFields(fields, item, rules)
		}
	case *peg.Choice:
		for _, opt := range e.Options {
			collectFields(fields, opt.Exp, rules)
		}
	case *peg.Option:
		collectFields(fields, e.Exp, rules)
	case *peg.Group:
		collectFields(fields, e.Exp, rules)
	case *peg.Closure:
		collectFields(fields, e.Exp, rules)
	case *peg.PositiveClosure:
		collectFields(fields, e.Exp, rules)
	case *peg.Gather:
		collectFields(fields, e.Exp, rules)
	case *peg.PositiveGather:
		collectFields(fields, e.Exp, rules)
	case *peg.Join:
		collectFields(fields, e.Exp, rules)
	case *peg.PositiveJoin:
		collectFields(fields, e.Exp, rules)
	case *peg.Optional:
		collectFields(fields, e.Exp, rules)
	case *peg.Override:
		collectFields(fields, e.Exp, rules)
	case *peg.OverrideList:
		collectFields(fields, e.Exp, rules)
	case *peg.Synth:
		collectFields(fields, e.Exp, rules)
	case *peg.SkipGroup:
		collectFields(fields, e.Exp, rules)
	}
}

// resolvedTypeName tries to determine the Go type name for a named element's
// inner expression. Looks through wrapper nodes (Optional, Choice, Closure, etc.)
// to find typed rule calls.
func resolvedTypeName(exp peg.Model, rules map[string]*peg.Rule) string {
	switch e := exp.(type) {
	case *peg.Call:
		if r, ok := rules[e.Name]; ok && len(r.Params) > 0 {
			return r.Params[0]
		}
	case *peg.Group:
		return resolvedTypeName(e.Exp, rules)
	case *peg.Sequence:
		for _, item := range e.Sequence {
			if tn := resolvedTypeName(item, rules); tn != "" {
				return tn
			}
		}
	case *peg.Optional:
		return resolvedTypeName(e.Exp, rules)
	case *peg.Closure:
		return resolvedTypeName(e.Exp, rules)
	case *peg.PositiveClosure:
		return resolvedTypeName(e.Exp, rules)
	case *peg.Gather:
		return resolvedTypeName(e.Exp, rules)
	case *peg.PositiveGather:
		return resolvedTypeName(e.Exp, rules)
	case *peg.Choice:
		for _, opt := range e.Options {
			if tn := resolvedTypeName(opt.Exp, rules); tn != "" {
				return tn
			}
		}
	}
	return ""
}

// isConstantText returns true when the expression is guaranteed to produce
// *trees.Text at runtime (Pattern or Token literals).
func isConstantText(exp peg.Model, rules map[string]*peg.Rule) bool {
	switch e := exp.(type) {
	case *peg.Pattern, *peg.Token:
		return true
	case *peg.Group:
		return isConstantText(e.Exp, rules)
	}
	return false
}

// isListExpr returns true when the expression wraps its inner in a list
// (Closure, Gather, etc.). Used to decide []*T vs *T for typed refs.
func isListExpr(exp peg.Model) bool {
	switch e := exp.(type) {
	case *peg.Closure, *peg.PositiveClosure, *peg.Gather, *peg.PositiveGather:
		return true
	case *peg.Group:
		return isListExpr(e.Exp)
	case *peg.Sequence:
		for _, item := range e.Sequence {
			if isListExpr(item) {
				return true
			}
		}
	}
	return false
}

func capitalise(s string) string {
	if s == "" {
		return s
	}
	firstRune, size := utf8.DecodeRuneInString(s)
	return string(unicode.ToUpper(firstRune)) + s[size:]
}
