name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish artifacts to PyPI?'
        required: true
        type: boolean
        default: false

jobs:
  build_artifacts:
    name: Build Matrix Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Set up uv
        uses: astral-sh/setup-uv@v5

      - name: Run Release Matrix
        run: python3 python/release.py
        env:
          CGO_ENABLED: 1

      - name: Build Source Distribution
        run: uv build --sdist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist/
          retention-days: 1

  publish_release:
    name: Publish to PyPI
    needs: [build_artifacts]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    # Run if triggered by a GitHub Release or if the manual dispatch flag is explicitly set to true
    if: ${{ github.event_name == 'release' || inputs.publish == true }}
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
